name: Home Assistant Add-on Issue
description: Report an issue specific to the Home Assistant add-on
title: "[ADD-ON] "
labels: ["addon", "homeassistant", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with the Home Assistant add-on! This template is specifically for add-on related issues.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have read the add-on documentation
          required: true
        - label: I have checked the Home Assistant logs
          required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you using?
      placeholder: "e.g., 2023.12.0"
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Add-on Version
      description: What version of the Command to MQTT add-on are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install the add-on?
      options:
        - Local add-on (copied to addons folder)
        - Custom repository (GitHub)
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the issue you're experiencing with the add-on.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Add-on Configuration
      description: Your add-on configuration (remove sensitive information)
      render: yaml
      placeholder: |
        mqtt:
          broker: "core-mosquitto"
          port: 1883
        commands:
          - name: "example"
            command: "uptime"
        # ... rest of config

  - type: textarea
    id: addon-logs
    attributes:
      label: Add-on Logs
      description: Logs from the Command to MQTT add-on (Supervisor → Add-ons → Command to MQTT → Log)
      render: text
      placeholder: |
        Paste add-on logs here...

  - type: textarea
    id: supervisor-logs
    attributes:
      label: Supervisor Logs (if relevant)
      description: Home Assistant Supervisor logs if the issue is related to add-on startup/installation
      render: text

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What architecture is your Home Assistant running on?
      options:
        - amd64
        - aarch64 (ARM 64-bit)
        - armv7 (ARM 32-bit)
        - armhf
        - i386
        - Unknown

  - type: dropdown
    id: installation-type
    attributes:
      label: Home Assistant Installation Type
      description: How is Home Assistant installed?
      options:
        - Home Assistant OS (Recommended)
        - Home Assistant Supervised
        - Home Assistant Container
        - Home Assistant Core

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Configure the add-on with...
        2. Start the add-on
        3. See error in logs...

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information about the issue.