name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version
          required: false

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How is the application installed?
      options:
        - Home Assistant Add-on
        - Docker Container
        - Binary/Compiled from source
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem.
      render: text
      placeholder: |
        Paste relevant log output here...

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your configuration file (remove sensitive information like passwords)
      render: yaml
      placeholder: |
        mqtt:
          broker: "localhost"
          port: 1883
        # ... rest of config

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Home Assistant OS
        - Other (please specify)

  - type: input
    id: architecture
    attributes:
      label: Architecture
      description: What architecture are you using?
      placeholder: "e.g., amd64, arm64, armv7"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.